#!/usr/bin/env python3
"""
init_project.py — ha-state-archive project initializer.

Creates the expected directory structure and a minimal retention policy
under --root. Never overwrites existing files or directories.

Usage:
    python3 init_project.py --root /volume1/Backups_HA/ha_backup_timeline
    python3 init_project.py --root /volume1/Backups_HA/ha_backup_timeline --apply

Exit codes:
    0  Dry-run completed (no changes made).
    0  Apply completed successfully.
    1  Apply completed with warnings (some items already existed, skipped).
    2  Fatal error (invalid arguments, permission denied, etc.).

Design rules:
    - Dry-run by default. --apply required for any filesystem write.
    - Never overwrites an existing file or directory.
    - Never deletes anything.
    - No implicit path discovery. --root is mandatory and explicit.
    - stdlib only.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


__version__ = "1.0.0"


# ---------------------------------------------------------------------------
# Directory structure
# ---------------------------------------------------------------------------

# (path_relative_to_root, required, description)
DIRECTORIES: list[tuple[str, bool, str]] = [
    ("versions",   True,  "immutable extracted versions"),
    ("quarantine", True,  "artifacts isolated pending purge"),
    ("config",     True,  "retention policy and credentials"),
    ("reports",    False, "audit and retention reports"),
    ("diffs",      False, "release diff outputs"),
    ("logs",       False, "pipeline execution logs"),
]


# ---------------------------------------------------------------------------
# Minimal retention policy
# ---------------------------------------------------------------------------

RETENTION_POLICY_FILENAME = "retention_policy.yaml"

RETENTION_POLICY_CONTENT = """\
# ==========================================================
# ha-state-archive — retention policy (minimal)
#
# Generated by ha-state-init. Edit to match your archive.
# This policy is deliberately conservative:
#   - purge is disabled (quarantine_candidate_delete: false)
#   - retention windows are generous
#   - no Arsenal-specific prefixes
#
# Run ha-state-retention --dry-run to preview classifications
# before enabling quarantine moves.
# ==========================================================


# ---------------------------------------------------------------------------
# Quarantine blast radius
# ---------------------------------------------------------------------------

# Only automatic backups are eligible for quarantine moves.
quarantine_only_automatic_backups: true

# CANDIDATE_DELETE artifacts are NOT quarantined until you validate
# that the retention windows below match your actual archive.
quarantine_candidate_delete: false


# ---------------------------------------------------------------------------
# Protected artifacts — preserved indefinitely
# ---------------------------------------------------------------------------

# Artifacts whose logical name starts with one of these prefixes
# are classified as KEEP_MAJOR and never quarantined.
# Add your major release prefixes here.

protected_name_prefixes: []


# ---------------------------------------------------------------------------
# Critical artifacts — preserved indefinitely
# ---------------------------------------------------------------------------

# Artifacts whose full name contains one of these patterns (case-insensitive)
# are classified as KEEP_CRITICAL and never quarantined.

critical_name_patterns:
  - "changelog"
  - "contract"


# ---------------------------------------------------------------------------
# Automatic backup identification
# ---------------------------------------------------------------------------

# Artifacts whose logical name starts with one of these prefixes
# are treated as automatic runtime backups.

automatic_backup_prefixes:
  - "Automatic_backup"
  - "Scheduled_backup"

# Number of most recent automatic backups to preserve.
automatic_backup_keep_count: 10


# ---------------------------------------------------------------------------
# Temporal retention windows
# ---------------------------------------------------------------------------

retention:

  # Keep every artifact during this period (days)
  keep_all_days: 14

  # Then keep one artifact per day (days from creation)
  keep_daily_days: 60

  # Then keep one artifact per week (days from creation)
  keep_weekly_days: 365
"""


# ---------------------------------------------------------------------------
# Result model
# ---------------------------------------------------------------------------

CREATE = "CREATE"
SKIP   = "SKIP"
DRYRUN = "DRY-RUN"
ERROR  = "ERROR"


def _record(results: list[tuple[str, str]], status: str, message: str) -> None:
    results.append((status, message))
    label = f"[{status}]"
    print(f"{label:<10} {message}")


def _created(results: list[tuple[str, str]], message: str) -> None:
    _record(results, CREATE, message)


def _skipped(results: list[tuple[str, str]], message: str) -> None:
    _record(results, SKIP, message)


def _dryrun(results: list[tuple[str, str]], message: str) -> None:
    _record(results, DRYRUN, message)


def _error(results: list[tuple[str, str]], message: str) -> None:
    _record(results, ERROR, message)


# ---------------------------------------------------------------------------
# Operations
# ---------------------------------------------------------------------------

def ensure_directory(path: Path, apply: bool, results: list[tuple[str, str]]) -> None:
    if path.exists():
        if path.is_dir():
            _skipped(results, f"directory already exists: {path}")
        else:
            _error(results, f"path exists but is not a directory: {path}")
        return

    if apply:
        try:
            path.mkdir(parents=True, exist_ok=True)
            _created(results, f"directory: {path}")
        except OSError as exc:
            _error(results, f"could not create directory {path}: {exc}")
    else:
        _dryrun(results, f"would create directory: {path}")


def ensure_retention_policy(
    config_dir: Path,
    apply: bool,
    results: list[tuple[str, str]],
) -> None:
    path = config_dir / RETENTION_POLICY_FILENAME

    if path.exists():
        _skipped(results, f"retention policy already exists: {path}")
        return

    if apply:
        if not config_dir.exists():
            _error(results, f"cannot write retention policy: config dir missing: {config_dir}")
            return
        try:
            path.write_text(RETENTION_POLICY_CONTENT, encoding="utf-8")
            _created(results, f"retention policy: {path}")
        except OSError as exc:
            _error(results, f"could not write retention policy {path}: {exc}")
    else:
        _dryrun(results, f"would create retention policy: {path}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="ha-state-init",
        description=(
            "Initialize the ha-state-archive project structure under --root. "
            "Never overwrites existing files or directories. "
            "Dry-run by default — use --apply to write."
        ),
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"ha-state-init {__version__}",
    )
    parser.add_argument(
        "--root",
        required=True,
        metavar="PATH",
        help="Root directory to initialize.",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        default=False,
        help="Write changes to disk. Without this flag, runs in dry-run mode.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    root = Path(args.root).expanduser().resolve()
    apply: bool = args.apply

    results: list[tuple[str, str]] = []

    mode = "APPLY" if apply else "DRY-RUN"
    print(f"ha-state-init {__version__} [{mode}]")
    print(f"root: {root}")
    print()

    if not apply:
        print("No changes will be made. Pass --apply to write.")
        print()

    ensure_directory(root, apply, results)

    for rel_path, _required, _description in DIRECTORIES:
        ensure_directory(root / rel_path, apply, results)

    ensure_retention_policy(root / "config", apply, results)

    print()

    has_error = any(s == ERROR  for s, _ in results)
    has_skip  = any(s == SKIP   for s, _ in results)

    creates = sum(1 for s, _ in results if s == CREATE)
    skips   = sum(1 for s, _ in results if s == SKIP)
    dryruns = sum(1 for s, _ in results if s == DRYRUN)
    errors  = sum(1 for s, _ in results if s == ERROR)

    if apply:
        print(f"Results: {creates} created, {skips} skipped, {errors} errors")
    else:
        print(f"Results: {dryruns} would be created, {skips} already exist")

    if has_error:
        print("Status: INCOMPLETE")
        return 2

    if has_skip and apply:
        print("Status: PARTIAL (some items already existed, skipped)")
        return 1

    if apply:
        print("Status: DONE")
        print()
        print(f"Run install_check.py --root {root} to verify the environment.")
    else:
        print("Status: DRY-RUN COMPLETE")
        print()
        print("Pass --apply to write changes.")

    return 0


if __name__ == "__main__":
    sys.exit(main())